# API parameters
[Binance] # API parameters for Binance
head = 'https://fapi.binance.com'
[Binance.futures_list]
method = 'GET'
query = '/fapi/v1/exchangeInfo'
[Binance.historical_data]
method = 'GET'
query = '/fapi/v1/klines'
[Binance.data.parameters]
symbol = ''
interval = ''
startTime = ''
endTime = ''
limit = ''
[FTX] # API parameters for FTX
head = 'https://ftx.com/api'
[FTX.futures_list]
method = 'GET'
query = '/futures'
[FTX.historical_data]
method = 'GET'
query = '/markets/{market_name}/candles'
replaceable = '{market_name}'
[FTX.data.parameters]
resolution = ''
start_time = ''
end_time = ''
