#================ API parameters ================#
[Binance] # API parameters for Binance
head = 'https://fapi.binance.com'
[Binance.futures_list]
method = 'GET'
[Binance.futures_list.request]
address = '/fapi/v1/exchangeInfo'
[Binance.historical_prices]
method = 'GET'
[Binance.historical_prices.request]
address = '/fapi/v1/klines'
# [Binance.historical_prices.parameters]
# symbol = ''
# interval = ''
# startTime = ''
# endTime = ''
# limit = ''
[Binance.historical_prices.parameters_mapping]
ticker = 'symbol'
candle_interval = 'interval'
start_time = 'startTime'
end_time = 'endTime'

[FTX] # API parameters for FTX
head = 'https://ftx.com/api'
[FTX.futures_list]
method = 'GET'
[FTX.futures_list.request]
address = '/futures'
[FTX.historical_prices]
method = 'GET'
[FTX.historical_prices.request]
address = '/markets/{market_name}/candles'
replaceable = '{market_name}'
# [FTX.historical_prices.parameters]
# resolution = ''
# start_time = ''
# end_time = ''
[FTX.historical_prices.parameters_mapping]
ticker = 'replaceable'
candle_interval = 'resolution'
start_time = 'start_time'
end_time = 'end_time'
[FTX.funding_rates]
method = 'GET'
[FTX.funding_rates.request]
address = '/funding_rates'
[FTX.funding_rates.parameters_mapping]
ticker = 'future'
start_time = 'start_time'
end_time = 'end_time'
